vnd.fact_stock_price_daily

In [1]:
import pandas as pd
pd.options.display.float_format = "{:,.2f}".format

df = pd.read_csv('raw/vnd_fact_stock_price_daily_20240630.csv')

df.describe()

,basicPrice,ceilingPrice,floorPrice,open,high,low,close,average,adOpen,adHigh,adLow,adClose,adAverage,nmVolume,nmValue,ptVolume,ptValue,change,adChange,pctChange
count,"32,301.00","32,301.00","32,301.00","32,301.00","32,301.00","32,301.00","32,301.00","32,301.00","32,301.00","32,301.00","32,301.00","32,301.00","32,301.00","32,301.00","32,301.00","32,301.00","32,301.00","32,301.00","32,301.00","32,301.00"
mean,20.99,23.54,18.43,21.02,21.26,20.78,21.09,21.01,20.88,21.12,20.64,20.95,20.87,"538,215.85","14,080,550,385.37","94,678.25","2,090,538,991.12",0.04,0.04,0.26
std,29.31,33.17,25.64,29.29,29.64,29.02,29.32,29.34,29.18,29.53,28.92,29.22,29.23,"2,330,546.97","65,400,627,194.07","1,498,747.86","31,024,994,901.71",1.05,1.05,3.67
min,0.00,0.00,0.00,0.00,0.00,0.00,0.20,0.00,0.00,0.00,0.00,0.20,0.00,0.00,0.00,0.00,0.00,-32.00,-32.00,-37.69
25%,7.00,7.90,5.80,7.00,7.03,6.90,7.05,6.97,7.00,7.00,6.90,7.00,6.94,0.00,0.00,0.00,0.00,-0.01,-0.01,-0.14
50%,12.80,14.40,11.20,12.80,13.00,12.60,12.90,12.80,12.80,12.99,12.60,12.90,12.80,"1,800.00","25,800,000.00",0.00,0.00,0.00,0.00,0.00
75%,24.70,27.95,21.60,24.85,25.00,24.50,24.90,24.78,24.70,25.00,24.45,24.70,24.64,"76,867.00","1,042,051,500.00",0.00,0.00,0.05,0.05,0.26
max,611.70,703.40,520.00,630.00,630.00,602.10,602.10,611.65,630.00,630.00,602.10,602.10,611.65,"69,364,500.00","1,776,774,590,000.00","103,678,064.00","1,879,980,764,800.00",38.60,38.60,50.00

In [30]:
import pandas as pd
pd.options.display.float_format = "{:,.2f}".format

df = pd.read_csv(r'raw\vnd_dim_financial_models_20240826.csv')

df.describe()

#find duplicate
df[df.duplicated(subset=['modelType','itemCode'])]

Empty DataFrame
Columns: [modelType, modelTypeName, modelVnDesc, modelEnDesc, companyForm, note, codeList, itemCode, itemVnName, itemEnName, displayOrder, displayLevel, formType, ratioCode, fk_date]
Index: []

In [8]:
import pandas as pd
pd.options.display.float_format = "{:,.2f}".format

df = pd.read_csv(r'raw\vnd_factless_financial_statements_20240831.csv')

df.describe()

#find duplicate
df[df.duplicated(subset=['code','itemCode','reportType','modelType','fiscalDate'])]

Empty DataFrame
Columns: [code, itemCode, reportType, modelType, numericValue, fiscalDate, createdDate, modifiedDate, fk_date]
Index: []

In [1]:
import pandas as pd

# Load the Excel file
file_path = r"D:\OneDrive - Northeastern University\MBS\Data\order history.xlsx"
df = pd.read_excel(file_path, sheet_name="Sheet1")

# Rename columns
df.rename(columns={
    "NGÀY ĐẶT LỆNH": "Date",
    "TÀI KHOẢN": "Account",
    "MÃ CK": "Symbol",
    "LOẠI GIAO DỊCH": "Side",
    "KHỐI LƯỢNG": "Order_quantity",
    "GIÁ": "Order_price",
    "TRẠNG THÁI": "Status",
    "SỐ HIỆU LỆNH": "Order_number",
    "KÊNH": "Channel",
    "KHỐI LƯỢNG KHỚP": "Match_quantity",
    "GIÁ KHỚP": "Match_price",
    "THỜI GIAN": "Match_time"
}, inplace=True)

# Convert data types
df["Date"] = pd.to_datetime(df["Date"], dayfirst=True, errors="coerce")
df["Order_quantity"] = pd.to_numeric(df["Order_quantity"], errors="coerce")
df["Order_price"] = pd.to_numeric(df["Order_price"], errors="coerce")
df["Match_quantity"] = pd.to_numeric(df["Match_quantity"], errors="coerce")
df["Match_price"] = pd.to_numeric(df["Match_price"], errors="coerce")
df["Match_time"] = pd.to_datetime(df["Match_time"], format="%H:%M:%S", errors="coerce").dt.time

# Convert text to uppercase
df["Side"] = df["Side"].str.upper()
df["Status"] = df["Status"].str.upper()

# Pad Account column with leading zeros
df["Account"] = df["Account"].astype(str).str.zfill(7)

# Reorder columns
columns_order = ["Date", "Account", "Symbol", "Side", "Order_quantity", "Order_price",
                 "Status", "Order_number", "Channel", "Match_quantity", "Match_price", "Match_time"]
df = df[columns_order]

# Display the final DataFrame
print(df.head())

        Date  Account Symbol Side  Order_quantity  Order_price   Status  \
0 2024-01-23  0385031    FRT  MUA             100       100.00  ĐÃ KHỚP
1 2024-01-16  0385039    EIB  BÁN             100        17.95  ĐÃ KHỚP
2 2024-11-01  0385039    EIB  MUA             300        20.40  ĐÃ KHỚP
3 2024-11-01  0385039    EIB  MUA             100        20.40  ĐÃ KHỚP
4 2024-11-01  0385039    FTS  BÁN             100        41.85  ĐÃ KHỚP

   Order_number     Channel  Match_quantity  Match_price Match_time
0          8792  New Mobile           100.0       100.00   09:18:09
1          2240  New Mobile           100.0        19.25   08:05:37
2         17630  New Mobile           300.0        19.90   09:47:13
3         17623  New Mobile           100.0        19.90   09:47:13
4         17452  New Mobile           100.0        44.05   09:46:30

In [10]:
import os
import pandas as pd
import re

def transform_file(file_path):
    # Load Excel file and select 'My Sheet'
    xls = pd.ExcelFile(file_path)
    df = pd.read_excel(xls, sheet_name='My Sheet', skiprows=3)

    # Rename columns
    df.columns = df.iloc[0]
    df = df[1:].reset_index(drop=True)

    # Handle NaN values and convert column types
    df['TÀI KHOẢN'] = df['TÀI KHOẢN'].astype('string')
    df['NGÀY THỰC HIỆN'] = df['NGÀY THỰC HIỆN'].astype('string')
    df['PHÁT SINH TĂNG'] = pd.to_numeric(df['PHÁT SINH TĂNG'], errors='coerce').fillna(0).astype('int64')
    df['PHÁT SINH GIẢM'] = pd.to_numeric(df['PHÁT SINH GIẢM'], errors='coerce').fillna(0).astype('int64')
    df['SỐ DƯ'] = pd.to_numeric(df['SỐ DƯ'], errors='coerce').fillna(0).astype('int64')
    df['NỘI DUNG'] = df['NỘI DUNG'].astype('string')

    # Remove bottom 3 rows
    df = df[:-3]

    # Remove 'STT' column if exists
    df.drop(columns=['STT'], errors='ignore', inplace=True)

    return df

def get_category(description):
    if 'Chuyển tiền mua' in description:
        return 'Stock Buy'
    elif 'Nhận tiền bán' in description:
        return 'Stock Sale'
    elif any(substring in description for substring in ['Phí bán', 'Phí dịch vụ bán']):
        return 'Sale Fee'
    elif any(substring in description for substring in ['Phí mua', 'Phí dịch vụ mua']):
        return 'Buy Fee'
    elif 'Phí GD (bao gồm Phí trả Sở)' in description:
        return 'Depository Trading Fee'
    elif 'MBS thu phí/nợ phí lưu ký chứng khoán' in description:
        return 'Depository Fee'
    elif 'Thu phí chuyển khoản bán CK theo quy định của TTLK' in description:
        return 'Depository Transfer Fee'
    elif 'Tạm thu thuế bán' in description:
        return 'Income Tax'
    elif any(substring in description for substring in ['Thuế TNCN 5% mã', 'Thu thuế cổ tức']):
        return 'Dividend Tax'
    elif 'MBS trả lãi tiền gửi' in description:
        return 'Demand Deposit Interest'
    elif 'Thu phi sao chep' in description:
        return 'Copy Fee'
    elif 'Giải ngân mua chứng khoán dịch vụ' in description:
        return 'Margin Release'
    elif 'Thu nợ gốc trong hạn' in description:
        return 'Margin Recover'
    elif any(substring in description for substring in ['Thu phí trong hạn MBLink', 'Thu phí trong hạn Mcredit']):
        return 'Margin Fee'
    elif 'Thu phí dịch vụ sức mua ứng trước' in description:
        return 'Cash Advanced Fee'
    elif any(substring in description for substring in ['Chuyen tien noi bo khi thuc hien copi24', 'Nop tien sao chep dich vu Copi24', 'Rut tien sao chep dich vu Copi24']):
        return 'Internal Transfer'
    elif description in ['back', 'c', 'chuyen', 'd', 'g']:
        return 'Internal Transfer'
    elif 'HOANG LE THANH CHUYEN TIEN TRACE' in description:
        return 'External Transfer'
    elif description in ['SOPHU REALTIME - NOP TIEN 005C038503 HOANG LE THANH', 'chuyen tien(29/12/2022 10:10:10)']:
        return 'External Transfer'
    elif any(substring in description for substring in ['Chi trả cổ tức', 'Tạm ứng cổ tức', 'Trả cổ tức']):
        return 'Cash Dividend'
    elif 'hoa hong gioi thieu cho KH theo CT' in description:
        return 'Referral Commission'
    else:
        return None

def get_regex(regex, text, group_number):
    match = re.search(regex, text)
    return match.group(group_number) if match else None

def process_folder(folder_path):
    all_data = []

    for file_name in os.listdir(folder_path):
        if file_name.endswith(('.xlsx', '.xls')):
            file_path = os.path.join(folder_path, file_name)
            df = transform_file(file_path)

            # Rename and clean columns
            df.rename(columns={
                'TÀI KHOẢN': 'Account',
                'NGÀY THỰC HIỆN': 'Date',
                'PHÁT SINH TĂNG': 'Credit',
                'PHÁT SINH GIẢM': 'Debit',
                'SỐ DƯ': 'Balance',
                'NỘI DUNG': 'Description'
            }, inplace=True)

            # Filter and transform
            df = df[df['Account'].notnull()]
            df['Account'] = df['Account'].apply(lambda x: str(x).zfill(7))
            df['Txtype'] = df.apply(lambda row: 'Debit' if row['Credit'] == 0 else 'Credit', axis=1)
            df['Amount'] = df[['Debit', 'Credit']].max(axis=1)
            df['Category'] = df['Description'].apply(get_category)

            # Drop unnecessary columns
            df.drop(columns=['Debit', 'Credit', 'Balance'], errors='ignore', inplace=True)

            # Filter out specific categories
            exclude_categories = ['Buy Fee', 'Depository Trading Fee', 'Income Tax', 'Margin Recover', 'Margin Release', 'Sale Fee', 'Stock Buy', 'Stock Sale']
            df = df[~df['Category'].isin(exclude_categories)]

            all_data.append(df)

    return pd.concat(all_data, ignore_index=True)

# Process folder and export result
folder_path = r"D:\OneDrive - Northeastern University\MBS\Data\sao_ke_tien"
final_df = process_folder(folder_path)
final_df

,Account,Date,Description,Txtype,Amount,Category
0,'0385031,21/11/2021,Fake begin cash for Power BI,Credit,16146055.0,None
1,'0385031,25/11/2021,MBS trả lãi tiền gửi tháng : 11/2021,Credit,1250.0,Demand Deposit Interest
2,'0385031,30/11/2021,MBS thu phí/nợ phí lưu ký chứng khoán (tháng: ...,Debit,16.0,Depository Fee
3,'0385031,27/12/2021,MBS trả lãi tiền gửi tháng : 12/2021,Credit,59.0,Demand Deposit Interest
4,'0385031,31/12/2021,MBS thu phí/nợ phí lưu ký chứng khoán (tháng: ...,Debit,84.0,Depository Fee
...,...,...,...,...,...,...
220,'0385031,02/01/2025,MBS thu phí/nợ phí lưu ký chứng khoán (tháng: ...,Debit,839.0,Depository Fee
221,'0385037,02/01/2025,MBS thu phí/nợ phí lưu ký chứng khoán (tháng: ...,Debit,335.0,Depository Fee
222,'0385031,07/01/2025,MBS THANH TOAN TIEU DIEM LOYALTY,Credit,15160.0,None
223,'0385031,08/01/2025,Thu phí chuyển khoản bán CK theo quy định của ...,Debit,660.0,Depository Transfer Fee
224,'0385031,15/01/2025,Thu phí chuyển khoản bán CK theo quy định của ...,Debit,30.0,Depository Transfer Fee