vnd.fact_stock_price_daily

In [1]:
import pandas as pd
pd.options.display.float_format = "{:,.2f}".format

df = pd.read_csv('raw/vnd_fact_stock_price_daily_20240630.csv')

df.describe()

,basicPrice,ceilingPrice,floorPrice,open,high,low,close,average,adOpen,adHigh,adLow,adClose,adAverage,nmVolume,nmValue,ptVolume,ptValue,change,adChange,pctChange
count,"32,301.00","32,301.00","32,301.00","32,301.00","32,301.00","32,301.00","32,301.00","32,301.00","32,301.00","32,301.00","32,301.00","32,301.00","32,301.00","32,301.00","32,301.00","32,301.00","32,301.00","32,301.00","32,301.00","32,301.00"
mean,20.99,23.54,18.43,21.02,21.26,20.78,21.09,21.01,20.88,21.12,20.64,20.95,20.87,"538,215.85","14,080,550,385.37","94,678.25","2,090,538,991.12",0.04,0.04,0.26
std,29.31,33.17,25.64,29.29,29.64,29.02,29.32,29.34,29.18,29.53,28.92,29.22,29.23,"2,330,546.97","65,400,627,194.07","1,498,747.86","31,024,994,901.71",1.05,1.05,3.67
min,0.00,0.00,0.00,0.00,0.00,0.00,0.20,0.00,0.00,0.00,0.00,0.20,0.00,0.00,0.00,0.00,0.00,-32.00,-32.00,-37.69
25%,7.00,7.90,5.80,7.00,7.03,6.90,7.05,6.97,7.00,7.00,6.90,7.00,6.94,0.00,0.00,0.00,0.00,-0.01,-0.01,-0.14
50%,12.80,14.40,11.20,12.80,13.00,12.60,12.90,12.80,12.80,12.99,12.60,12.90,12.80,"1,800.00","25,800,000.00",0.00,0.00,0.00,0.00,0.00
75%,24.70,27.95,21.60,24.85,25.00,24.50,24.90,24.78,24.70,25.00,24.45,24.70,24.64,"76,867.00","1,042,051,500.00",0.00,0.00,0.05,0.05,0.26
max,611.70,703.40,520.00,630.00,630.00,602.10,602.10,611.65,630.00,630.00,602.10,602.10,611.65,"69,364,500.00","1,776,774,590,000.00","103,678,064.00","1,879,980,764,800.00",38.60,38.60,50.00

In [30]:
import pandas as pd
pd.options.display.float_format = "{:,.2f}".format

df = pd.read_csv(r'raw\vnd_dim_financial_models_20240826.csv')

df.describe()

#find duplicate
df[df.duplicated(subset=['modelType','itemCode'])]

Empty DataFrame
Columns: [modelType, modelTypeName, modelVnDesc, modelEnDesc, companyForm, note, codeList, itemCode, itemVnName, itemEnName, displayOrder, displayLevel, formType, ratioCode, fk_date]
Index: []

In [8]:
import pandas as pd
pd.options.display.float_format = "{:,.2f}".format

df = pd.read_csv(r'raw\vnd_factless_financial_statements_20240831.csv')

df.describe()

#find duplicate
df[df.duplicated(subset=['code','itemCode','reportType','modelType','fiscalDate'])]

Empty DataFrame
Columns: [code, itemCode, reportType, modelType, numericValue, fiscalDate, createdDate, modifiedDate, fk_date]
Index: []

Import Excel to Postgres

In [17]:
import xlwings as xw
import pandas as pd

file_location = "D:\OneDrive - Northeastern University\MBS\dim_financial_models_kan62.xlsx"
wb = xw.Book(file_location)

sheet1 = wb.sheets['Sheet1']
df = pd.DataFrame(sheet1['A1'].expand().value)
new_header = df.iloc[0] #grab the first row for the header
df = df[1:] #take the data less the header row
df.columns = new_header #set the header row as the df header

### Close and Save Workbook
wb.save()
# wb.close()
wb.app.quit()

,model_type,item_en_name,item_vn_name,model_type_name,display_order,display_level,item_code,item_vn_name_clean,display_level_clean
1,1.0,Current Assets,Tài sản ngắn hạn,BALANCESHEET,10.0,1.0,11000.0,A. Tài sản lưu động và đầu tư ngắn hạn,None
2,1.0,Cash and Cash Equivalents,Tiền và các khoản tương đương tiền,BALANCESHEET,20.0,2.0,11100.0,I. Tiền và các khoản tương đương tiền,None
3,1.0,Cash,Tiền,BALANCESHEET,30.0,3.0,11110.0,1. Tiền,None
4,1.0,Cash equivalents,Các khoản tương đương tiền,BALANCESHEET,70.0,3.0,11120.0,2. Các khoản tương đương tiền,None
5,1.0,Short term financial investment,Các khoản đầu tư tài chính ngắn hạn,BALANCESHEET,80.0,2.0,11200.0,II. Các khoản đầu tư tài chính ngắn hạn,None
...,...,...,...,...,...,...,...,...,...
1100,413.0,Net Cashflow from Financing activities,Lưu chuyển tiền thuần từ hoạt động tài chính,CASHFLOW,380.0,0.0,34000.0,None,None
1101,413.0,Net Cash and Cash equivalents during the period,Lưu chuyển tiền thuần trong kỳ,CASHFLOW,390.0,0.0,35000.0,None,None
1102,413.0,Cash and cash equivalents at beginning of year,Tiền và tương đương tiền đầu kỳ,CASHFLOW,400.0,0.0,36000.0,None,None
1103,413.0,Effect of foreign exchange differences,Ảnh hưởng của thay đổi tỷ giá hối đoái quy đổi...,CASHFLOW,410.0,0.0,36100.0,None,None
1104,413.0,Cash and Cash equivalents at end of year,Tiền và tương đương tiền cuối kỳ,CASHFLOW,420.0,0.0,37000.0,None,None